name: Rust Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: http2amcp
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: http2amcp.exe

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Get the current date and time
        id: datetime
        run: echo "::set-output name=datetime::$(date +'%Y%m%d.%H%M')"

      - name: Create and Upload Release
        if: matrix.os == 'ubuntu-latest'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/${{ matrix.target }}/release/${{ matrix.binary_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: release-${{ steps.datetime.outputs.datetime }}
          name: Release ${{ steps.datetime.outputs.datetime }}
          draft: false
          prerelease: false
